// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$LambdaReasonReactNative = require("./Home.bs.js");

function app() {
  return ReasonReact.element(undefined, undefined, Home$LambdaReasonReactNative.make(/* array */[]));
}

exports.app = app;
/* ReasonReact Not a pure module */
