// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

var primary = /* String */Block.__(0, ["#D9491D"]);

var light = /* String */Block.__(0, ["#F4F4F4"]);

var dark = /* String */Block.__(0, ["#3D3D3B"]);

var secondary = /* String */Block.__(0, ["#525F7F"]);

var gray = /* String */Block.__(0, ["#7F8489"]);

exports.primary = primary;
exports.light = light;
exports.dark = dark;
exports.secondary = secondary;
exports.gray = gray;
/* No side effect */
