// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var ActionButton$LambdaReasonReactNative = require("./ActionButton.bs.js");

var container = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.alignItems(/* Center */2),
      /* [] */0
    ]);

var code = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginTop(/* Pt */Block.__(0, [30])),
      /* :: */[
        Style$BsReactNative.fontSize(/* Float */Block.__(0, [30])),
        /* :: */[
          Style$BsReactNative.color(/* String */Block.__(0, ["red"])),
          /* [] */0
        ]
      ]
    ]);

var text = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginBottom(/* Pt */Block.__(0, [30])),
      /* :: */[
        Style$BsReactNative.color(/* String */Block.__(0, ["red"])),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* container */container,
  /* code */code,
  /* text */text
];

var component = ReasonReact.statelessComponent("ErrorMessage");

function make(message, code$1, onRefresh, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(code), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[String(code$1)])),
                              ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(text), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[message])),
                              ReasonReact.element(undefined, undefined, ActionButton$LambdaReasonReactNative.make(onRefresh, "Refresh", /* array */[]))
                            ]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* container Not a pure module */
