// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Random = require("bs-platform/lib/js/random.js");

var data = /* :: */[
  /* record */[
    /* firstName */"Jakub",
    /* lastName */"Klobus"
  ],
  /* :: */[
    /* record */[
      /* firstName */"Matt",
      /* lastName */"Zatorski"
    ],
    /* :: */[
      /* record */[
        /* firstName */"Luke",
        /* lastName */"Czyszczonik"
      ],
      /* :: */[
        /* record */[
          /* firstName */"Adam",
          /* lastName */"Malysz"
        ],
        /* :: */[
          /* record */[
            /* firstName */"Lambd",
            /* lastName */"Up"
          ],
          /* :: */[
            /* record */[
              /* firstName */"Mike",
              /* lastName */"Grabowski"
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

function getData() {
  Random.self_init(/* () */0);
  var randomValue = Random.$$int(4);
  if (randomValue !== 0) {
    if (randomValue !== 1) {
      return /* Response */Block.__(0, [
                200,
                data
              ]);
    } else {
      return /* Response */Block.__(0, [
                202,
                data
              ]);
    }
  } else {
    return /* Error */Block.__(1, [
              404,
              "Cannot find data"
            ]);
  }
}

exports.data = data;
exports.getData = getData;
/* No side effect */
