// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Text$BsReactNative = require("bs-react-native/src/components/text.js");
var View$BsReactNative = require("bs-react-native/src/components/view.js");
var Image$BsReactNative = require("bs-react-native/src/components/image.js");
var Modal$BsReactNative = require("bs-react-native/src/components/modal.js");
var Style$BsReactNative = require("bs-react-native/src/style.js");
var Colors$LambdaReasonReactNative = require("./Colors.bs.js");
var ActionButton$LambdaReasonReactNative = require("./ActionButton.bs.js");

var container = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.marginHorizontal(/* Pt */Block.__(0, [25])),
      /* :: */[
        Style$BsReactNative.marginVertical(/* Pt */Block.__(0, [70])),
        /* :: */[
          Style$BsReactNative.padding(/* Pt */Block.__(0, [10])),
          /* :: */[
            Style$BsReactNative.borderRadius(10),
            /* :: */[
              Style$BsReactNative.borderWidth(1),
              /* :: */[
                Style$BsReactNative.borderColor(Colors$LambdaReasonReactNative.gray),
                /* :: */[
                  Style$BsReactNative.flex(1),
                  /* :: */[
                    Style$BsReactNative.backgroundColor(Colors$LambdaReasonReactNative.light),
                    /* :: */[
                      Style$BsReactNative.alignItems(/* Center */2),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var name = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.padding(/* Pt */Block.__(0, [15])),
      /* :: */[
        Style$BsReactNative.color(Colors$LambdaReasonReactNative.gray),
        /* :: */[
          Style$BsReactNative.fontSize(/* Float */Block.__(0, [25])),
          /* [] */0
        ]
      ]
    ]);

var button = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.position(/* Absolute */0),
      /* :: */[
        Style$BsReactNative.bottom(/* Pt */Block.__(0, [10])),
        /* [] */0
      ]
    ]);

var image = Style$BsReactNative.style(/* :: */[
      Style$BsReactNative.width(/* Pt */Block.__(0, [200])),
      /* [] */0
    ]);

var Styles = /* module */[
  /* container */container,
  /* name */name,
  /* button */button,
  /* image */image
];

var component = ReasonReact.statelessComponent("PersonModal");

function make(person, onClose, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return ReasonReact.element(undefined, undefined, Modal$BsReactNative.make(/* slide */-20462287, undefined, true, undefined, undefined, onClose, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(container), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(name), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[person[/* firstName */0]])),
                                        ReasonReact.element(undefined, undefined, Text$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(name), undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* array */[person[/* firstName */0]])),
                                        ReasonReact.element(undefined, undefined, Image$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, /* URI */Block.__(0, [Image$BsReactNative.imageURISource("https://api.adorable.io/avatars/285/" + String(person[/* id */2]), undefined, undefined, undefined, undefined, undefined, undefined, 200, 200, /* () */0)]), Js_primitive.some(image), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[])),
                                        ReasonReact.element(undefined, undefined, View$BsReactNative.make(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, Js_primitive.some(button), undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(/* array */[ReasonReact.element(undefined, undefined, ActionButton$LambdaReasonReactNative.make(onClose, "Close", /* array */[]))]))
                                      ]))]));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.Styles = Styles;
exports.component = component;
exports.make = make;
/* container Not a pure module */
